const hmsHospitals = [
  {
    id: "default-hospital",
    hospitalId: "default-hospital",
    name: "CareBridge Central Hospital",
    summary:
      "A full-service clinic and diagnostics hub for appointments, lab tests, and follow-up care.",
    status: "active",
    public: true,
    managerIds: ["demo-manager"],
    rating: 4.8,
    reviewCount: 312,
    openingHours: "09:00 - 19:00",
    heroImage: "/brand/hms/hospital-discovery-hero.png",
    profileImage: "/brand/hms/hospital-diagnostics-suite.png",
    contact: {
      phone: "+91 98765 43210",
      email: "central@carebridge.example",
      website: "https://carebridge.example",
    },
    location: {
      city: "New Delhi",
      area: "Connaught Place",
      address: "22 Wellness Avenue, Connaught Place, New Delhi, India",
      lat: 28.6315,
      lng: 77.2167,
      geoHash: "ttnfvp",
    },
    specialties: ["Cardiology", "Neurology", "Dermatology", "General Medicine"],
  },
  {
    id: "noida-care-hospital",
    hospitalId: "noida-care-hospital",
    name: "CareBridge Noida Wellness Hospital",
    summary:
      "A high-throughput outpatient hospital with pediatrics, dermatology, diagnostics, and wellness testing.",
    status: "active",
    public: true,
    managerIds: ["demo-manager"],
    rating: 4.6,
    reviewCount: 184,
    openingHours: "08:30 - 20:00",
    heroImage: "/brand/hms/hospital-care-team.png",
    profileImage: "/brand/hms/hospital-care-team.png",
    contact: {
      phone: "+91 98111 22334",
      email: "noida@carebridge.example",
      website: "https://carebridge.example/noida",
    },
    location: {
      city: "Noida",
      area: "Sector 62",
      address: "A-18 Health Park, Sector 62, Noida, India",
      lat: 28.627,
      lng: 77.3722,
      geoHash: "ttngn3",
    },
    specialties: ["Pediatrics", "Dermatology", "Orthopedics", "Diagnostics"],
  },
  {
    id: "gurugram-medtech-hospital",
    hospitalId: "gurugram-medtech-hospital",
    name: "CareBridge Gurugram MedTech Hospital",
    summary:
      "A technology-forward hospital for neurology, orthopedics, imaging, and preventive health packages.",
    status: "active",
    public: true,
    managerIds: ["demo-manager"],
    rating: 4.7,
    reviewCount: 227,
    openingHours: "09:00 - 21:00",
    heroImage: "/brand/hms/hospital-diagnostics-suite.png",
    profileImage: "/brand/hms/test-booking-lab.png",
    contact: {
      phone: "+91 98222 33445",
      email: "gurugram@carebridge.example",
      website: "https://carebridge.example/gurugram",
    },
    location: {
      city: "Gurugram",
      area: "Cyber City",
      address: "5 MedTech Plaza, Cyber City, Gurugram, India",
      lat: 28.4949,
      lng: 77.0888,
      geoHash: "ttn8z9",
    },
    specialties: ["Neurology", "Orthopedics", "Radiology", "Preventive Health"],
  },
];

const hmsMedia = {
  "default-hospital": [
    {
      id: "central-hero",
      type: "image",
      title: "Central care lounge",
      url: "/brand/hms/hospital-discovery-hero.png",
      sortOrder: 1,
      public: true,
    },
    {
      id: "central-diagnostics",
      type: "image",
      title: "Diagnostics and consulting",
      url: "/brand/hms/hospital-diagnostics-suite.png",
      sortOrder: 2,
      public: true,
    },
  ],
  "noida-care-hospital": [
    {
      id: "noida-care-team",
      type: "image",
      title: "Noida clinical team",
      url: "/brand/hms/hospital-care-team.png",
      sortOrder: 1,
      public: true,
    },
    {
      id: "noida-family-care",
      type: "image",
      title: "Family care",
      url: "/brand/hms/hospital-discovery-hero.png",
      sortOrder: 2,
      public: true,
    },
  ],
  "gurugram-medtech-hospital": [
    {
      id: "gurugram-tech-care",
      type: "image",
      title: "MedTech diagnostics",
      url: "/brand/hms/hospital-diagnostics-suite.png",
      sortOrder: 1,
      public: true,
    },
    {
      id: "gurugram-departments",
      type: "image",
      title: "Specialist departments",
      url: "/brand/hms/test-booking-lab.png",
      sortOrder: 2,
      public: true,
    },
  ],
};

const hmsTests = [
  {
    id: "test-cbc",
    name: "Complete Blood Count",
    category: "Pathology",
    durationMinutes: 15,
    price: 450,
    instructions: "No fasting required.",
    image: "/brand/hms/test-booking-lab.png",
    status: "active",
    public: true,
  },
  {
    id: "test-lipid-profile",
    name: "Lipid Profile",
    category: "Pathology",
    durationMinutes: 15,
    price: 800,
    instructions: "Fasting for 10-12 hours is recommended.",
    image: "/brand/hms/test-booking-lab.png",
    status: "active",
    public: true,
  },
  {
    id: "test-mri-brain",
    name: "MRI Brain",
    category: "Radiology",
    durationMinutes: 45,
    price: 6500,
    instructions: "Carry prior reports and remove metal accessories.",
    image: "/brand/hms/hospital-diagnostics-suite.png",
    status: "active",
    public: true,
  },
  {
    id: "test-ecg",
    name: "ECG",
    category: "Cardiology",
    durationMinutes: 10,
    price: 350,
    instructions: "Avoid heavy exercise before the test.",
    image: "/brand/hms/hospital-care-team.png",
    status: "active",
    public: true,
  },
];

const hospitalTestIds = {
  "default-hospital": ["test-cbc", "test-lipid-profile", "test-mri-brain", "test-ecg"],
  "noida-care-hospital": ["test-cbc", "test-lipid-profile", "test-ecg"],
  "gurugram-medtech-hospital": ["test-cbc", "test-mri-brain", "test-ecg"],
};

const hmsTestSlots = [
  ["slot-central-cbc-1", "default-hospital", "test-cbc", "2026-05-08", "09:30", 8],
  ["slot-central-cbc-2", "default-hospital", "test-cbc", "2026-05-08", "12:30", 6],
  ["slot-central-mri-1", "default-hospital", "test-mri-brain", "2026-05-09", "10:00", 3],
  ["slot-central-ecg-1", "default-hospital", "test-ecg", "2026-05-09", "15:00", 10],
  ["slot-noida-cbc-1", "noida-care-hospital", "test-cbc", "2026-05-08", "10:00", 7],
  ["slot-noida-lipid-1", "noida-care-hospital", "test-lipid-profile", "2026-05-10", "08:30", 5],
  ["slot-gurugram-mri-1", "gurugram-medtech-hospital", "test-mri-brain", "2026-05-10", "11:00", 2],
  ["slot-gurugram-ecg-1", "gurugram-medtech-hospital", "test-ecg", "2026-05-11", "16:00", 9],
].map(([id, hospitalId, testId, date, startTime, capacity]) => ({
  id,
  hospitalId,
  testId,
  date,
  startTime,
  capacity,
  booked: 0,
  availableCapacity: capacity,
  status: "open",
  public: true,
}));

module.exports = {
  hmsHospitals,
  hmsMedia,
  hmsTests,
  hospitalTestIds,
  hmsTestSlots,
};
