# Generated by Django 4.2 on 2024-11-12 08:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='admin')),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('text', models.CharField(default='N/A', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=122)),
                ('category', models.CharField(max_length=122)),
                ('image', models.ImageField(null=True, upload_to='blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('location', models.CharField(default='N/A', max_length=122)),
                ('department', models.CharField(default='N/A', max_length=122)),
                ('doctor', models.CharField(default='N/A', max_length=122)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('problem', models.TextField()),
                ('username', models.CharField(default='rahul', max_length=60)),
                ('today_appointments_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='confirmed', max_length=10)),
                ('is_patient', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_logo', models.ImageField(null=True, upload_to='logos')),
                ('new_favicon', models.ImageField(null=True, upload_to='favicons')),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('timings_weekday', models.CharField(max_length=50)),
                ('timings_weekend', models.CharField(max_length=50)),
                ('slogan_title', models.CharField(max_length=50)),
                ('slogan_text', models.CharField(default='HI', max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('email_address', models.EmailField(default='N/A', max_length=150)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationQueryM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(default=None, max_length=122)),
                ('contact', models.CharField(max_length=10)),
                ('intrest', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(default='N/A', max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('phone', models.CharField(default='1234567890', max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DateSlotModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('slot_number', models.IntegerField(editable=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ManageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('status', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ManagePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='Booking', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=122)),
                ('date_of_birth', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('gender', models.CharField(default='N/A', max_length=10, null=True)),
                ('age', models.CharField(blank=True, default='N/A', max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='patients')),
                ('contact', models.CharField(default='N/A', max_length=10)),
                ('email', models.EmailField(default='N/A', max_length=122)),
                ('address', models.CharField(default='N/A', max_length=122)),
                ('city', models.CharField(default='N/A', max_length=122)),
                ('state', models.CharField(default='N/A', max_length=60)),
                ('zipcode', models.CharField(default='N/A', max_length=6)),
                ('blood_group', models.CharField(default='N/A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('text', models.CharField(default='N/A', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('image', models.ImageField(null=True, upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('username', models.CharField(default='N/A', max_length=122)),
                ('gender', models.CharField(default='N/A', max_length=122)),
                ('email', models.EmailField(default='N/A', max_length=122)),
                ('role', models.CharField(default='N/A', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('yoe', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=122)),
                ('code', models.IntegerField(max_length=6)),
                ('phone', models.CharField(default='1234567890', max_length=10)),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('image', models.ImageField(null=True, upload_to='Staff')),
                ('location', models.CharField(default='N/A', max_length=250)),
                ('department', models.CharField(default='N/A', max_length=250)),
                ('state', models.CharField(default='N/A', max_length=60)),
                ('country', models.CharField(default='N/A', max_length=60)),
                ('zipcode', models.CharField(default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_vendor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'permissions': [('can_change_is_active', 'Can change the is_active status of other users')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubSlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('date_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_slots', to='DrConsult.dateslotmodel')),
            ],
            options={
                'unique_together': {('date_slot', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='SlotGenerationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('check_days', models.BooleanField(default=False)),
                ('until_date', models.DateField(null=True)),
                ('auto_generate', models.BooleanField(default=False)),
                ('last_generated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrConsult.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='patient_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='DrConsult.patient')),
            ],
            options={
                'verbose_name': 'Patient Document',
                'verbose_name_plural': 'Patient Documents',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('slot_number', models.IntegerField(editable=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.staff')),
            ],
        ),
        migrations.AddField(
            model_name='dateslotmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.staff'),
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('location', models.CharField(default='N/A', max_length=122)),
                ('department', models.CharField(default='N/A', max_length=122)),
                ('doctor', models.CharField(default='N/A', max_length=122)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('problem', models.TextField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrConsult.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrConsult.subslotmodel'),
        ),
    ]
