# Generated by Django 4.2 on 2024-11-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='vendor')),
                ('role', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=6)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
