# Generated by Django 4.2 on 2024-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0002_vendoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='acheivements',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='staff',
            name='intro',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, default='N/A', max_length=122),
        ),
        migrations.AlterField(
            model_name='staff',
            name='code',
            field=models.IntegerField(default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='staff',
            name='yoe',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
