# Generated by Django 4.2 on 2024-11-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0003_staff_acheivements_staff_intro_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='acheivements',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='intro',
            new_name='introduction',
        ),
    ]
