# Generated by Django 4.2 on 2024-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0004_rename_acheivements_staff_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.CharField(default='N/A', max_length=5000),
        ),
    ]
