# Generated by Django 4.2 on 2024-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0005_alter_staff_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.CharField(default='<p><br></p>', max_length=5000),
        ),
    ]
