# Generated by Django 4.2 on 2024-11-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0006_alter_staff_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrConsult.patient')),
            ],
        ),
    ]
