# Generated by Django 4.2 on 2024-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='problem',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
