# Generated by Django 4.2 on 2024-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0008_alter_booking_problem_alter_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
