# Generated by Django 4.2 on 2024-11-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0010_feedback_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='zipcode',
            new_name='code',
        ),
    ]
