# Generated by Django 4.2 on 2024-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0011_rename_zipcode_admin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='code',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='code',
        ),
    ]
