# Generated by Django 4.2 on 2024-11-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0012_rename_code_admin_zipcode_remove_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subroles',
            field=models.JSONField(null=True),
        ),
    ]
