# Generated by Django 4.2 on 2024-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0013_customuser_roles_customuser_subroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subroles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
