# Generated by Django 4.2 on 2024-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0014_alter_customuser_roles_alter_customuser_subroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='slogan_text',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
