# Generated by Django 4.2 on 2024-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0015_alter_configuration_slogan_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageBlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='achievements',
            field=models.TextField(default='<p><br></p>'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
