# Generated by Django 4.2 on 2024-12-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0016_manageblogcategories_alter_staff_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
