# Generated by Django 4.2 on 2024-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0017_alter_blogs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.CharField(default='N/A', max_length=5000),
        ),
    ]
