# Generated by Django 4.2 on 2025-01-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0018_alter_blogs_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='zipcode',
            new_name='code',
        ),
    ]
