# Generated by Django 4.2 on 2025-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0019_rename_zipcode_staff_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='department',
            field=models.CharField(default=' ', max_length=122),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.CharField(default=' ', max_length=122),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(default=' ', max_length=122),
        ),
        migrations.AlterField(
            model_name='booking',
            name='problem',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
