# Generated by Django 4.2 on 2025-01-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0020_alter_booking_department_alter_booking_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupNotificationsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_account_SID', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
