# Generated by Django 4.2 on 2025-01-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0021_setupnotificationsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='amount',
            field=models.IntegerField(default=500),
        ),
    ]
