# Generated by Django 4.2 on 2025-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0022_staff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='email_address',
            field=models.EmailField(default=' ', max_length=150),
        ),
    ]
