# Generated by Django 4.2 on 2025-01-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0023_alter_configuration_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='currency_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='configuration',
            name='currency_symbol',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
