# Generated by Django 4.2 on 2025-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0024_configuration_currency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
