# Generated by Django 4.2 on 2025-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0025_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageblogcategories',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='managedepartment',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='managelocation',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
