# Generated by Django 4.2 on 2025-04-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0026_alter_manageblogcategories_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='zipcode',
            new_name='code',
        ),
    ]
