# Generated by Django 4.2 on 2025-04-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrConsult', '0027_rename_zipcode_admin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoruser',
            old_name='zipcode',
            new_name='code',
        ),
    ]
