ROLES = {
    # "0": "Dashboard",
    "1": "Configurations",
    # "2": "Manage Vendor",
    "3": "Manage Staff",
    "4": "Manage Appointments",
    "5": "Consultation Queries",
    "6": "Manage Content",
    "7": "Manage Blogs",
    "8": "Manage Services",
    "9": "Manage Enquiries",
    "10": "Manage Location",
    "11": "Manage Department",
    "12": "Manage Feedback",
    "13": "Manage Slots",
    "14": "Manage Holidays",    
    "15": "My Profile",
    "16": "Change Password",
    "17": "Manage Notifications",
    "18": "Manage Blog Categories",
    "19": "Manage Patients",
    # "18": "Logout",
}

SUBROLES = {
    # "1": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel" },
    # "2": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Status", 8:"Role" },
    "3": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Change status", 8:"Assign role",10:"Account Status"},
    "4": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel Booking", 11:"Patient Details"},
    "5": { 3:"Delete", 4:"View", 6:"Reply" },
    "6": { 2:"Edit"},
    "7": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View",},
    "8": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View",7:"Change status"},
    "9": { 3:"Delete", 4:"View",},
    "10": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Change status"},
    "11": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Change status"},
    "12": {  4:"View", 7:"Change status"},
    "13": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Change status", 9:"Slot-Setting"},
    "18": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 7:"Change status"},
    "19": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View",7:"Change status"},

    # "14": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel"},
    # "15": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel"},
    # "16": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel"},
    # "17": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel"},
    # "18": { 1:"Add", 2:"Edit", 3:"Delete", 4:"View", 5:"Cancel"},
}